/*
 * rep_pay_stu.java
 *
 * Created on May 10, 2011, 1:17 PM
 */
package view.Reports;

import control.Mainwindowcontrol;
import control.OccationalLogics;
import control.rep_pay_stuControl;
import java.awt.event.KeyEvent;

/**
 *
 * @author  gihan
 */
public final class rep_pay_stu extends javax.swing.JPanel {

    rep_pay_stuControl pay_stucontrol;
    OccationalLogics logics;
    int usertype;

    public rep_pay_stu() {
        
        initComponents();
        logics = new OccationalLogics();
        usertype = logics.getGetCategory("Student");
        searchscoral.setVisible(false);
        repaint();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchscoral = new javax.swing.JScrollPane();
        searchlist1 = new javax.swing.JList();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tsid = new javax.swing.JTextField();
        bview = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jyear = new com.toedter.calendar.JYearChooser();
        tsearch = new javax.swing.JTextField();
        Report_tab = new javax.swing.JTabbedPane();

        setBackground(new java.awt.Color(153, 180, 209));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchlist1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchlist1MouseClicked(evt);
            }
        });
        searchlist1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchlist1KeyReleased(evt);
            }
        });
        searchscoral.setViewportView(searchlist1);

        add(searchscoral, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 55, 270, 10));

        jPanel4.setBackground(new java.awt.Color(181, 201, 243));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true), "Select the Student", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel21.setText("Student Name");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, -1, -1));

        tsid.setFont(new java.awt.Font("Times New Roman", 1, 14));
        tsid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tsid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsidActionPerformed(evt);
            }
        });
        tsid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tsidKeyReleased(evt);
            }
        });
        jPanel4.add(tsid, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 90, -1));

        bview.setFont(new java.awt.Font("Dialog", 1, 12));
        bview.setText("View");
        bview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bviewActionPerformed(evt);
            }
        });
        jPanel4.add(bview, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 30, 90, -1));

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("ID");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(691, 30, 30, 20));
        jPanel4.add(jyear, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 30, 90, 25));

        tsearch.setFont(new java.awt.Font("Dialog", 1, 12));
        tsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tsearchActionPerformed(evt);
            }
        });
        tsearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tsearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tsearchKeyTyped(evt);
            }
        });
        jPanel4.add(tsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, 270, 25));

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1290, 80));

        Report_tab.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        add(Report_tab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1290, 600));
    }// </editor-fold>//GEN-END:initComponents

private void bviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bviewActionPerformed
    pay_stucontrol = new rep_pay_stuControl();
    pay_stucontrol.viewReport(tsid.getText(), Report_tab, jyear.getYear());



}//GEN-LAST:event_bviewActionPerformed

private void tsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsearchActionPerformed
}//GEN-LAST:event_tsearchActionPerformed

private void tsearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsearchKeyReleased
    Mainwindowcontrol.personSeach(searchscoral, tsearch.getText(), searchlist1, usertype, 0);
    Mainwindowcontrol.settingFocus(evt, searchlist1);

}//GEN-LAST:event_tsearchKeyReleased

private void tsearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsearchKeyTyped
}//GEN-LAST:event_tsearchKeyTyped

private void tsidKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tsidKeyReleased
    OccationalLogics.validateTextDouble(evt);
}//GEN-LAST:event_tsidKeyReleased

private void searchlist1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchlist1KeyReleased
    if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
        tsearch.setText(searchlist1.getSelectedValue().toString());
        tsid.setText(tsearch.getText().split("-")[1]);
        searchscoral.setVisible(false);

    } else {
        Mainwindowcontrol.list_key_release(evt, tsearch);
    }
}//GEN-LAST:event_searchlist1KeyReleased

private void searchlist1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchlist1MouseClicked
    tsearch.setText(searchlist1.getSelectedValue().toString());
    tsid.setText(tsearch.getText().split("-")[1]);
    searchlist1.setVisible(false);
    searchscoral.setVisible(false);
}//GEN-LAST:event_searchlist1MouseClicked

private void tsidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tsidActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_tsidActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Report_tab;
    private javax.swing.JButton bview;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JPanel jPanel4;
    private com.toedter.calendar.JYearChooser jyear;
    private javax.swing.JList searchlist1;
    private javax.swing.JScrollPane searchscoral;
    private javax.swing.JTextField tsearch;
    private javax.swing.JTextField tsid;
    // End of variables declaration//GEN-END:variables
}
