/*
 * editstaff.java
 *
 * Created on June 3, 2011, 9:47 PM
 */
package view;

import control.OccationalLogics;
import control.editpesonDetails;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author  gihan
 */
public final class editstaff extends javax.swing.JPanel {

    JComponent comp[] = new JComponent[12];

    public editstaff() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfname = new javax.swing.JTextField();
        tmname = new javax.swing.JTextField();
        tlname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        taddno = new javax.swing.JTextField();
        tstreet = new javax.swing.JTextField();
        tcity = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tcontact = new javax.swing.JTextField();
        id = new javax.swing.JLabel();
        bviewclass1 = new javax.swing.JButton();
        bviewclass2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        tepfnumber = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        radiomarried = new javax.swing.JRadioButton();
        radiounmarried = new javax.swing.JRadioButton();
        tdesignation = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tbsalary = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        tusername = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        bsave = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        tpassword = new javax.swing.JPasswordField();
        trepassword = new javax.swing.JPasswordField();
        usrname1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(191, 205, 219));

        jPanel1.setBackground(new java.awt.Color(191, 205, 219));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Main Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel2.setText("First Name");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel3.setText("Middle Name");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel4.setText("Last Name");

        tfname.setFont(new java.awt.Font("Times New Roman", 1, 14));

        tmname.setFont(new java.awt.Font("Times New Roman", 1, 14));

        tlname.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel5.setText("Address No");

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel6.setText("Street");

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel7.setText("City");

        taddno.setFont(new java.awt.Font("Times New Roman", 1, 14));

        tstreet.setFont(new java.awt.Font("Times New Roman", 1, 14));

        tcity.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel12.setText("Contact No");

        tcontact.setFont(new java.awt.Font("Times New Roman", 1, 14));

        id.setFont(new java.awt.Font("Dialog", 1, 12));
        id.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        id.setText("000");
        id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(26, 26, 26)
                        .addComponent(tcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(23, 23, 23)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tcity, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(taddno, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tstreet, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(28, 28, 28)
                                .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tlname, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                                    .addComponent(tmname, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))))
                        .addGap(56, 56, 56))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tmname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tlname, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(taddno, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tstreet, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tcity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tcontact, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        bviewclass1.setFont(new java.awt.Font("Dialog", 1, 12));
        bviewclass1.setText("Get Full Report");
        bviewclass1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bviewclass1MouseEntered(evt);
            }
        });
        bviewclass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bviewclass1ActionPerformed(evt);
            }
        });

        bviewclass2.setFont(new java.awt.Font("Dialog", 1, 12));
        bviewclass2.setText("Full Report - PDF");
        bviewclass2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bviewclass2MouseEntered(evt);
            }
        });
        bviewclass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bviewclass2ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(191, 205, 219));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "Work Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel21.setText("EPF Number");

        tepfnumber.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel15.setText("Designation");

        radiomarried.setBackground(new java.awt.Color(152, 175, 222));
        buttonGroup1.add(radiomarried);
        radiomarried.setFont(new java.awt.Font("Dialog", 1, 12));
        radiomarried.setText("Married");

        radiounmarried.setBackground(new java.awt.Color(152, 175, 222));
        buttonGroup1.add(radiounmarried);
        radiounmarried.setFont(new java.awt.Font("Dialog", 1, 12));
        radiounmarried.setSelected(true);
        radiounmarried.setText("Unmarried");

        tdesignation.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel18.setText("Basic Salary");

        tbsalary.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel19.setText("LKR");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(17, 17, 17)
                        .addComponent(tepfnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(18, 18, 18)
                        .addComponent(tbsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel19))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(radiomarried)
                        .addGap(26, 26, 26)
                        .addComponent(radiounmarried))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(17, 17, 17)
                        .addComponent(tdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(tepfnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radiomarried)
                    .addComponent(radiounmarried))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tdesignation, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(tbsalary, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(191, 205, 219));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)), "System Details", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Arial", 1, 12), new java.awt.Color(0, 0, 255))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel25.setText("Username");

        tusername.setEditable(false);
        tusername.setFont(new java.awt.Font("Times New Roman", 1, 14));

        jLabel26.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel26.setText("Old -Password");

        bsave.setFont(new java.awt.Font("Dialog", 1, 12));
        bsave.setText("Edit");
        bsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsaveActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 12));
        jLabel27.setText("New-Password");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tpassword, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel6Layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(trepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bsave, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tusername, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(tpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(trepassword, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(bsave)
                .addContainerGap(135, Short.MAX_VALUE))
        );

        usrname1.setFont(new java.awt.Font("Dialog", 1, 12));
        usrname1.setForeground(new java.awt.Color(255, 0, 0));
        usrname1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        usrname1.setText(" ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bviewclass2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bviewclass1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(usrname1, javax.swing.GroupLayout.DEFAULT_SIZE, 363, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usrname1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bviewclass1)
                    .addComponent(bviewclass2))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

private void bviewclass1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bviewclass1MouseEntered
// TODO add your handling code here:
}//GEN-LAST:event_bviewclass1MouseEntered

private void bviewclass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bviewclass1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_bviewclass1ActionPerformed

private void bviewclass2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bviewclass2MouseEntered
// TODO add your handling code here:
}//GEN-LAST:event_bviewclass2MouseEntered

private void bviewclass2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bviewclass2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_bviewclass2ActionPerformed

private void bsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsaveActionPerformed
    if (OccationalLogics.showOption("Yes", "No") == 0) {

if(!tpassword.getText().isEmpty() && !trepassword.getText().isEmpty()){
    if(tpassword.getText().equals(pass)){
        pass = trepassword.getText();
    JOptionPane.showMessageDialog(null, "Password Changed", "Info", JOptionPane.INFORMATION_MESSAGE);
    }else{
    JOptionPane.showMessageDialog(null, "Password MisMatch, password will not change", "Info", JOptionPane.WARNING_MESSAGE);
    }

}else if(!tpassword.getText().isEmpty() || !trepassword.getText().isEmpty()){
    JOptionPane.showMessageDialog(null, "should fill both password fields", "Info", JOptionPane.INFORMATION_MESSAGE);
}
        comp[0] = tfname;
        comp[1] = id;
        comp[2] = tmname;
        comp[3] = tlname;
        comp[4] = taddno;
        comp[5] = tstreet;
        comp[6] = tcity;
        comp[7] = tcontact;
        comp[8] = tepfnumber;
        comp[9] = radiomarried;
        comp[10] = tdesignation;
        comp[11] = tbsalary;


        if (aThis.editStaff(comp ,pass)) {
            JOptionPane.showMessageDialog(null, "Data Editing success", "Edit", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Sorry, Unexpected error occured", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }
}//GEN-LAST:event_bsaveActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bsave;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton bviewclass1;
    private javax.swing.JButton bviewclass2;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton radiomarried;
    private javax.swing.JRadioButton radiounmarried;
    private javax.swing.JTextField taddno;
    private javax.swing.JTextField tbsalary;
    private javax.swing.JTextField tcity;
    private javax.swing.JTextField tcontact;
    private javax.swing.JTextField tdesignation;
    private javax.swing.JTextField tepfnumber;
    private javax.swing.JTextField tfname;
    private javax.swing.JTextField tlname;
    private javax.swing.JTextField tmname;
    private javax.swing.JPasswordField tpassword;
    private javax.swing.JPasswordField trepassword;
    private javax.swing.JTextField tstreet;
    private javax.swing.JTextField tusername;
    private javax.swing.JLabel usrname1;
    // End of variables declaration//GEN-END:variables
    private editpesonDetails aThis;
    String pass;

    public void setData(String[] UserDetails, editpesonDetails aThis) {
        this.aThis = aThis;
        id.setText(UserDetails[1]);
        tfname.setText(UserDetails[0]);
        tmname.setText(UserDetails[2]);
        tlname.setText(UserDetails[3]);
        taddno.setText(UserDetails[4]);
        tstreet.setText(UserDetails[5]);
        tcity.setText(UserDetails[6]);
        tcontact.setText(UserDetails[7]);
        tepfnumber.setText(UserDetails[8]);
        String status = UserDetails[10];
        radiomarried.setSelected(status.equals("Married"));
        radiounmarried.setSelected(status.equals("Single"));
        tdesignation.setText(UserDetails[9]);
        tbsalary.setText(UserDetails[11]);
        tusername.setText(UserDetails[12]);
        pass = UserDetails[13];


    }
}
